### ISSUE TITLE
Как определить, на каком физическом жёстком диске находится раздел с файловой системой? Как можно идентифицировать этот носитель без выключения сервера?

### ISSUE THREAD

**Issue by hellstad** [Swfuse/devops-interview#2]
Добрый день. Отличный сборник вопросов. 
Добавьте пожалуйста ответ, если посчитаете правильным.

Как определить, на каком физическом жёстком диске находится раздел с файловой системой? Как можно идентифицировать этот носитель без выключения сервера?
mount - посмотреть название блочного устройства.
smartctl -a /dev/sda | grep -e "Serial Number" -e "Device Model"  -e "Model Family" -e "User Capacity"
Получим фирму, модель и серийный номер и размер диска. Достаточно для идентификации.
Как вариант сделать dmesg | grep sda, но там будет только модель диска.

**Comment by Swfuse** [comment]
Здравствуйте. 
Благодарю.

В целом да, ответ нормальный. Добавил его. 

Пишите ещё. Пулреквесты на исправление так же приветствуются.
